import type { WorkflowStageDefinition } from "./types";

const ids = [
  "reference-validation", "transcript-cleaning", "reference-segmentation", "competitor-dna", "opportunity-map", "originality-review",
  "research-source-intake", "claim-map", "outline", "fact-review", "retention-review", "character-preparation", "visual-routing",
  "asset-concepts", "asset-acquisition", "voice-generation", "subtitle-preparation", "timeline-assembly", "preview-render", "qa", "capcut-draft", "packaging-export"
] as const;
const names: Record<string, string> = {
  "reference-validation": "Reference Validation", "transcript-cleaning": "Transcript Cleaning", "reference-segmentation": "Reference Segmentation", "competitor-dna": "Competitor DNA", "opportunity-map": "Opportunity Map", "originality-review": "Originality Review", "research-source-intake": "Research Source Intake", "claim-map": "Claim Map", outline: "Outline", "fact-review": "Fact Review", "retention-review": "Retention Review", "character-preparation": "Character Preparation", "visual-routing": "Visual Routing", "asset-concepts": "Asset Concepts", "asset-acquisition": "Asset Acquisition", "voice-generation": "Voice Generation", "subtitle-preparation": "Subtitle Preparation", "timeline-assembly": "Timeline Assembly", "preview-render": "Preview Render", qa: "QA", "capcut-draft": "CapCut Draft", "packaging-export": "Packaging Export"
};
const routes: Record<string, string> = { "reference-validation": "reference-intake", "transcript-cleaning": "competitor-dna", "reference-segmentation": "competitor-dna", "competitor-dna": "competitor-dna", "opportunity-map": "idea-lab", "originality-review": "idea-lab", "research-source-intake": "advanced-pipeline", "claim-map": "advanced-pipeline", outline: "script", "fact-review": "script", "retention-review": "script", "character-preparation": "channel-profiles", "visual-routing": "visuals", "asset-concepts": "visuals", "asset-acquisition": "visuals", "voice-generation": "voice", "subtitle-preparation": "timeline", "timeline-assembly": "timeline", "preview-render": "final-preview", qa: "qa", "capcut-draft": "export", "packaging-export": "export" };
export const legacyWorkflowStageDefinitions: WorkflowStageDefinition[] = ids.map((id, index) => ({ id, name: names[id]!, order: 100 + index, screenRoute: routes[id] ?? "advanced-pipeline", dependsOn: id === "packaging-export" ? ["qa"] : index === 0 ? ["reference-intake"] : [ids[index - 1]!], requiredInputTypes: ["legacy.input"], outputArtifactTypes: ["legacy.output"], runnerId: `legacy-${id}`, executionKind: id === "voice-generation" ? "provider_audio" : id === "asset-acquisition" ? "provider_image" : "local_deterministic", ...(id === "voice-generation" ? { requiredCapability: "audio" } : id === "asset-acquisition" ? { requiredCapability: "image" } : {}), approvalRequired: true, ...(id === "capcut-draft" ? { optional: true } : {}), invalidates: index + 1 < ids.length ? [ids[index + 1]!] : [] }));
