import type { WorkflowStageDefinition } from "./types";
import { legacyWorkflowStageDefinitions } from "./legacyWorkflowRegistry";

export const perReferenceArtifactStages: ReadonlySet<string> = new Set(["reference-intake", "transcript-cleaning", "reference-segmentation", "competitor-dna"]);
export const semiAutomaticCheckpointIds: ReadonlySet<string> = new Set(["reference-intake", "idea-lab", "script", "image-review", "reference-validation", "asset-review", "voice-generation", "preview-render"]);
export const semiAutomaticAutomaticStageIds: ReadonlySet<string> = new Set(["idea-lab", "story-architecture", "script", "timing", "director-analysis", "scene-plan", "shot-plan", "prompt-preparation", "batch-planner", "reference-validation", "transcript-cleaning", "reference-segmentation", "competitor-dna", "opportunity-map", "originality-review", "research-source-intake", "claim-map", "outline", "fact-review", "retention-review", "visual-routing", "asset-concepts", "asset-acquisition", "subtitle-preparation", "timeline-assembly", "qa", "capcut-draft", "packaging-export"]);

const stage = (definition: WorkflowStageDefinition): WorkflowStageDefinition => definition;

// This is the only registry used by new projects. Legacy stage IDs are retained in
// saved project payloads and normalized separately for backward compatibility.
export const workflowStageDefinitions = [
  stage({ id: "project-setup", name: "Project Brief", order: 1, screenRoute: "project-overview", dependsOn: [], requiredInputTypes: ["project.setup"], outputArtifactTypes: ["project.brief"], runnerId: null, executionKind: "manual_input", approvalRequired: true, userInteractionRequired: true, invalidates: ["reference-intake", "idea-lab", "story-architecture", "script"] }),
  stage({ id: "reference-intake", name: "Reference / Research", order: 2, screenRoute: "reference-intake", dependsOn: ["project-setup"], requiredInputTypes: ["project.brief"], outputArtifactTypes: ["reference.research"], runnerId: null, executionKind: "manual_input", approvalRequired: true, applicability: "reference", userInteractionRequired: true, invalidates: ["idea-lab", "story-architecture", "script"] }),
  stage({ id: "idea-lab", name: "Idea Lab", order: 3, screenRoute: "idea-lab", dependsOn: ["project-setup"], requiredInputTypes: ["project.brief", "reference.research"], outputArtifactTypes: ["idea.candidates"], runnerId: "idea-lab-text-provider", executionKind: "provider_text", requiredCapability: "text", approvalRequired: true, applicability: "not_existing_script", userInteractionRequired: true, invalidates: ["story-architecture"] }),
  stage({ id: "story-architecture", name: "Story Architecture", order: 4, screenRoute: "script", dependsOn: ["idea-lab"], requiredInputTypes: ["idea.approved"], outputArtifactTypes: ["story.architecture"], runnerId: "outline-text-provider", executionKind: "provider_text", requiredCapability: "text", approvalRequired: true, applicability: "not_existing_script", userInteractionRequired: true, invalidates: ["script"] }),
  stage({ id: "script", name: "Script", order: 5, screenRoute: "script", dependsOn: ["story-architecture"], requiredInputTypes: ["story.architecture"], outputArtifactTypes: ["script"], runnerId: "script-text-provider", executionKind: "provider_text", requiredCapability: "text", approvalRequired: true, userInteractionRequired: true, invalidates: ["timing"] }),
  stage({ id: "timing", name: "Timing", order: 6, screenRoute: "script", dependsOn: ["script"], requiredInputTypes: ["script.approved"], outputArtifactTypes: ["timing"], runnerId: null, executionKind: "manual_input", approvalRequired: true, userInteractionRequired: true, invalidates: ["director-analysis"] }),
  stage({ id: "director-analysis", name: "Director Analysis", order: 7, screenRoute: "scenes", dependsOn: ["timing"], requiredInputTypes: ["script.approved", "timing.approved"], outputArtifactTypes: ["director.analysis"], runnerId: "scene-plan-text-provider", executionKind: "provider_text", requiredCapability: "text", approvalRequired: true, userInteractionRequired: true, invalidates: ["scene-plan"] }),
  stage({ id: "scene-plan", name: "Scene Map", order: 8, screenRoute: "scenes", dependsOn: ["director-analysis"], requiredInputTypes: ["director.analysis"], outputArtifactTypes: ["scene.map"], runnerId: "scene-plan-text-provider", executionKind: "provider_text", requiredCapability: "text", approvalRequired: true, userInteractionRequired: true, invalidates: ["shot-plan"] }),
  stage({ id: "shot-plan", name: "Storyboard / Keyframes", order: 9, screenRoute: "shots", dependsOn: ["scene-plan"], requiredInputTypes: ["scene.map"], outputArtifactTypes: ["storyboard.keyframes"], runnerId: null, executionKind: "manual_input", approvalRequired: true, userInteractionRequired: true, invalidates: ["prompt-preparation"] }),
  stage({ id: "prompt-preparation", name: "Prompt Compiler", order: 10, screenRoute: "visuals", dependsOn: ["shot-plan"], requiredInputTypes: ["storyboard.keyframes"], outputArtifactTypes: ["image.prompts"], runnerId: "prompt-preparation-text-provider", executionKind: "provider_text", requiredCapability: "text", approvalRequired: true, userInteractionRequired: true, invalidates: ["batch-planner"] }),
  stage({ id: "batch-planner", name: "Batch Planner", order: 11, screenRoute: "visuals", dependsOn: ["prompt-preparation"], requiredInputTypes: ["image.prompts"], outputArtifactTypes: ["gglab.batch"], runnerId: null, executionKind: "manual_input", approvalRequired: true, userInteractionRequired: true, invalidates: ["gglab-generation-gate"] }),
  stage({ id: "gglab-generation-gate", name: "GG Lab Generation Gate", order: 12, screenRoute: "visuals", dependsOn: ["batch-planner"], requiredInputTypes: ["gglab.batch"], outputArtifactTypes: ["external.images"], runnerId: null, executionKind: "manual_input", approvalRequired: true, userInteractionRequired: true, invalidates: ["asset-review"] }),
  stage({ id: "asset-review", name: "Image Review", order: 13, screenRoute: "assets", dependsOn: ["gglab-generation-gate"], requiredInputTypes: ["external.images"], outputArtifactTypes: ["images.approved"], runnerId: "asset-review-user-action", executionKind: "manual_input", approvalRequired: true, userInteractionRequired: true, invalidates: ["production-handoff"] }),
  stage({ id: "production-handoff", name: "Production Handoff", order: 14, screenRoute: "project-overview", dependsOn: ["asset-review"], requiredInputTypes: ["images.approved"], outputArtifactTypes: ["production.handoff"], runnerId: null, executionKind: "manual_input", approvalRequired: true, userInteractionRequired: true, invalidates: [] })
] as const satisfies WorkflowStageDefinition[];

export type WorkflowStageId = (typeof workflowStageDefinitions)[number]["id"];
export function getWorkflowStageDefinition(stageId: string): WorkflowStageDefinition | undefined { return workflowStageDefinitions.find((stage) => stage.id === stageId) ?? legacyWorkflowStageDefinitions.find((stage) => stage.id === stageId); }
export function getDownstreamWorkflowStageIds(stageId: string): ReadonlySet<string> { const result = new Set<string>(); const visit = (id: string) => { for (const next of getWorkflowStageDefinition(id)?.invalidates ?? []) if (!result.has(next)) { result.add(next); visit(next); } }; visit(stageId); return result; }
export function getWorkflowStageImpactIds(stageId: string): ReadonlySet<string> { return new Set([stageId, ...getDownstreamWorkflowStageIds(stageId)]); }
export function workflowStageIds(): string[] { return workflowStageDefinitions.map((stage) => stage.id); }
