import type { ProviderCredentialStore, TextCertificationStore } from "@lsf/db";
import { ideaLabOutputSchema } from "@lsf/domain";
import { NineRouterClient, NineRouterTextResponseError } from "@lsf/providers";
import { loadNineRouterTextCertification } from "./nineRouterTextCertificationService";

export class IdeaLabError extends Error { constructor(readonly category: "capability_not_verified" | "credential_missing" | "provider_failed" | "invalid_json" | "invalid_output", message: string) { super(message); } }
interface TextClient { createResponseText(input: { model: string; input: string }): Promise<{ text: string; returnedModelId?: string }>; }
export async function runIdeaLab(input: { opportunityMap: Record<string, unknown>; topic: string; profile: Record<string, unknown>; format: string; language: string; targetDuration: string; credentialStore: ProviderCredentialStore; certificationStore: TextCertificationStore; createClient?: (config: { baseUrl: string; apiKey: string }) => TextClient }) {
  const certification = await loadNineRouterTextCertification({ credentialStore: input.credentialStore, certificationStore: input.certificationStore }); if (certification.status !== "verified") throw new IdeaLabError("capability_not_verified", "A verified text-model certification is required before Idea Lab can run.");
  const settings = input.credentialStore.loadProviderCredentialSettings("9router"); const apiKey = await input.credentialStore.resolveProviderSecret("9router"); if (!settings?.textModel || !apiKey) throw new IdeaLabError("credential_missing", "The selected text model or credential is unavailable.");
  let response: { text: string; returnedModelId?: string }; try { response = await (input.createClient?.({ baseUrl: settings.baseUrl, apiKey }) ?? new NineRouterClient({ baseUrl: settings.baseUrl, apiKey, timeoutMs: 60_000 })).createResponseText({ model: settings.textModel, input: `Generate exactly 12 original YouTube idea candidates from this approved Opportunity Map and active channel context: 4 low-risk evergreen (researchRisk low), 4 medium-difficulty (medium), and 4 stretch (high). Do not copy competitor titles or thumbnails, promise guarantees, defame, or auto-select an idea. Return only strict JSON {candidates:[...]}.\n${JSON.stringify({ opportunityMap: input.opportunityMap, topic: input.topic, profile: input.profile, format: input.format, language: input.language, targetDuration: input.targetDuration })}` }); } catch (error) { throw new IdeaLabError("provider_failed", error instanceof NineRouterTextResponseError ? `Idea Lab provider request failed: ${error.status}.` : "Idea Lab provider request failed."); }
  let parsed: unknown; try { parsed = JSON.parse(response.text.trim()); } catch { throw new IdeaLabError("invalid_json", "Idea Lab returned invalid JSON."); } const result = ideaLabOutputSchema.safeParse(parsed); if (!result.success) throw new IdeaLabError("invalid_output", "Idea Lab returned an invalid candidate set."); return { output: result.data, ...(response.returnedModelId ? { returnedModelId: response.returnedModelId } : {}) };
}
