import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { MemoryKeychain, openFactoryDatabase, ProviderCredentialStore, TextCertificationStore } from "@lsf/db";
import { fingerprintBaseUrl } from "./nineRouterTextCertificationService";
import { runOpportunityMap } from "./opportunityMapService";

async function setup() { const db = openFactoryDatabase(join(mkdtempSync(join(tmpdir(), "lsf-map-")), "factory.sqlite")); const credentialStore = new ProviderCredentialStore(db, new MemoryKeychain()); const certificationStore = new TextCertificationStore(db); await credentialStore.saveProviderCredential({ providerId: "9router", baseUrl: "http://127.0.0.1:20128/v1", textModel: "map-v1" }, "sk-secret"); certificationStore.saveTextCertificationRecord({ id: "cert-1", providerId: "9router", configuredModelId: "map-v1", baseUrlFingerprint: fingerprintBaseUrl("http://127.0.0.1:20128/v1")!, credentialVersionRef: credentialStore.loadProviderCredentialVersionRef("9router"), endpointStrategy: "responses", implementationVersion: "text-certification-v1", exactTextTest: { status: "passed", latencyMs: 1 }, strictJsonTest: { status: "passed", latencyMs: 1 }, overallStatus: "verified", testedAt: "2026-07-30T00:00:00.000Z" }); return { db, credentialStore, certificationStore }; }
const artifact = { id: "artifact-1", payload: { referenceId: "ref-1" } };
const entry = { text: "Explore unanswered viewer questions", sourceReferenceIds: ["ref-1"], sourceArtifactIds: ["artifact-1"], confidence: "low" as const };
const output = { sharedPatterns: [], overusedPatterns: [], underservedViewerQuestions: [entry], evidenceGaps: [], differentiationDirections: [], riskyDirections: [], recommendedContentSpaces: [] };
describe("opportunity map service", () => { it("requires low confidence for a single approved DNA artifact", async () => { const { db, credentialStore, certificationStore } = await setup(); const result = await runOpportunityMap({ dnaArtifacts: [artifact], credentialStore, certificationStore, createClient: () => ({ createResponseText: async () => ({ text: JSON.stringify(output) }) }) }); expect(result.output.underservedViewerQuestions[0]?.confidence).toBe("low"); db.close(); }); it("fails when a single-source response claims high confidence", async () => { const { db, credentialStore, certificationStore } = await setup(); await expect(runOpportunityMap({ dnaArtifacts: [artifact], credentialStore, certificationStore, createClient: () => ({ createResponseText: async () => ({ text: JSON.stringify({ ...output, underservedViewerQuestions: [{ ...entry, confidence: "high" }] }) }) }) })).rejects.toMatchObject({ category: "invalid_output" }); db.close(); }); });
