import type { ProviderCredentialStore, TextCertificationStore } from "@lsf/db";
import { outlineOutputSchema, resolveChannelPromptContext, type ChannelDna, type ChannelPromptProfile, type ResolvedChannelPromptContext } from "@lsf/domain";
import { NineRouterClient, NineRouterTextResponseError } from "@lsf/providers";
import { loadNineRouterTextCertification } from "./nineRouterTextCertificationService";

export class OutlineError extends Error { constructor(readonly category: "capability_not_verified" | "credential_missing" | "provider_failed" | "invalid_json" | "invalid_output", message: string) { super(message); } }
interface TextClient { createResponseText(input: { model: string; input: string }): Promise<{ text: string; returnedModelId?: string }>; }

export async function runOutline(input: { idea: Record<string, unknown>; claims: Array<{ id: string; state: string; approvalState: string }>; profile: Record<string, unknown>; channelDna?: ChannelDna; promptContext?: ResolvedChannelPromptContext; targetDuration: string; language: string; credentialStore: ProviderCredentialStore; certificationStore: TextCertificationStore; createClient?: (config: { baseUrl: string; apiKey: string }) => TextClient }) {
  const channelDna = input.channelDna ?? (input.profile as { channelDna?: ChannelDna }).channelDna;
  const profilePrompt = (input.profile as { id?: string; niche?: string; channelPromptProfile?: ChannelPromptProfile }).channelPromptProfile;
  const promptContext = input.promptContext ?? (profilePrompt && (input.profile as { id?: string }).id
    ? resolveChannelPromptContext({ channelId: (input.profile as { id: string }).id, profile: profilePrompt, taskType: "story" })
    : undefined);
  const certification = await loadNineRouterTextCertification({ credentialStore: input.credentialStore, certificationStore: input.certificationStore }); if (certification.status !== "verified") throw new OutlineError("capability_not_verified", "A verified text-model certification is required before Outline can run.");
  const settings = input.credentialStore.loadProviderCredentialSettings("9router"); const apiKey = await input.credentialStore.resolveProviderSecret("9router"); if (!settings?.textModel || !apiKey) throw new OutlineError("credential_missing", "The selected text model or credential is unavailable.");
  let response: { text: string; returnedModelId?: string }; try { response = await (input.createClient?.({ baseUrl: settings.baseUrl, apiKey }) ?? new NineRouterClient({ baseUrl: settings.baseUrl, apiKey, timeoutMs: 60_000 })).createResponseText({ model: settings.textModel, input: `Create an outline only from the approved idea and channel profile. The target language is ${input.language}. This is a hard requirement: write every human-readable field in ${input.language}; do not write the outline in English unless English is the target language. Respect only the resolved channel content identity and content lane when choosing section purposes and proof objects. Return strict JSON {"sections":[...]}. Every section must use exactly {"id":string,"order":integer starting at 0,"purpose":string,"keyPoint":string,"linkedClaimIds":string[],"dramaticFunction":string,"estimatedSeconds":positive integer,"openLoop"?:string,"proofObjects":string[]}. linkedClaimIds may be empty because this workflow does not use web research or Claim Map. Do not fact-check, browse, create claims, scenes, shots, or image prompts. Respect the requested duration.\n${JSON.stringify({ idea: input.idea, contentIdentity: promptContext?.contentLane, channelPromptContext: promptContext, targetDuration: input.targetDuration, targetLanguage: input.language })}` }); } catch (error) { throw new OutlineError("provider_failed", error instanceof NineRouterTextResponseError ? `Outline provider request failed: ${error.status}.` : "Outline provider request failed."); }
  let parsed: unknown; try { parsed = JSON.parse(response.text.trim()); } catch { throw new OutlineError("invalid_json", "Outline returned invalid JSON."); }
  const result = outlineOutputSchema.safeParse(parsed); if (!result.success) throw new OutlineError("invalid_output", "Outline returned an invalid structured output.");
  const allowedClaims = new Set(input.claims.filter((claim) => claim.approvalState === "allowed" && claim.state === "verified").map((claim) => claim.id));
  if (result.data.sections.some((section) => section.linkedClaimIds.some((id) => !allowedClaims.has(id)))) throw new OutlineError("invalid_output", "Outline linked unsupported or unknown claims.");
  const orders = result.data.sections.map((section) => section.order); if (new Set(orders).size !== orders.length || orders.some((order, index) => order !== index)) throw new OutlineError("invalid_output", "Outline sections must use consecutive order values.");
  return { output: result.data, ...(response.returnedModelId ? { returnedModelId: response.returnedModelId } : {}) };
}
