import type { ProviderCredentialStore, TextCertificationStore } from "@lsf/db";
import { outlineOutputSchema } from "@lsf/domain";
import { TextProviderError, type TextProvider } from "@lsf/providers";
import { resolveActiveTextProvider } from "./textProviderService";

export class OutlineError extends Error { constructor(readonly category: "capability_not_verified" | "credential_missing" | "provider_failed" | "invalid_json" | "invalid_output", message: string) { super(message); } }
type TextClient = Pick<TextProvider, "generateStructured">;

export async function runOutline(input: { idea: Record<string, unknown>; claims: Array<{ id: string; state: string; approvalState: string }>; profile: Record<string, unknown>; targetDuration: string; language: string; credentialStore: ProviderCredentialStore; certificationStore: TextCertificationStore; createClient?: (config: { baseUrl: string; apiKey: string }) => TextClient }) {
  let configured: { provider: TextProvider; model: string }; try { configured = await resolveActiveTextProvider({ credentialStore: input.credentialStore, certificationStore: input.certificationStore }); } catch (error) { throw new OutlineError(error instanceof TextProviderError ? "capability_not_verified" : "credential_missing", "Verified Cockpit text capability is required before Outline can run."); }
  const prompt = `Create an outline only from the approved idea and channel profile. The target language is ${input.language}. This is a hard requirement: write every human-readable field in ${input.language}; do not write the outline in English unless English is the target language. Return strict JSON {"sections":[...]}. Every section must use exactly {"id":string,"order":integer starting at 0,"purpose":string,"keyPoint":string,"linkedClaimIds":string[],"dramaticFunction":string,"estimatedSeconds":positive integer,"openLoop"?:string,"proofObjects":string[]}. linkedClaimIds may be empty because this workflow does not use web research or Claim Map. Do not fact-check, browse, create claims, scenes, shots, or image prompts. Respect the requested duration.\n${JSON.stringify({ idea: input.idea, profile: input.profile, targetDuration: input.targetDuration, targetLanguage: input.language })}`;
  let response: { data: ReturnType<typeof outlineOutputSchema.parse>; returnedModelId?: string }; try { const client = input.createClient?.({ baseUrl: "", apiKey: "" }); response = client ? await client.generateStructured({ model: configured.model, input: prompt, schema: outlineOutputSchema, timeoutMs: 60_000 }) : await configured.provider.generateStructured({ model: configured.model, input: prompt, schema: outlineOutputSchema, timeoutMs: 60_000 }); } catch (error) { if (error instanceof TextProviderError && error.code === "invalid_json") throw new OutlineError("invalid_json", "Outline returned invalid JSON."); if (error instanceof TextProviderError && error.code === "schema_validation_failed") throw new OutlineError("invalid_output", "Outline returned an invalid structured output."); throw new OutlineError("provider_failed", "Outline text provider request failed."); }
  const result = response.data;
  const allowedClaims = new Set(input.claims.filter((claim) => claim.approvalState === "allowed" && claim.state === "verified").map((claim) => claim.id));
  if (result.sections.some((section) => section.linkedClaimIds.some((id) => !allowedClaims.has(id)))) throw new OutlineError("invalid_output", "Outline linked unsupported or unknown claims.");
  const orders = result.sections.map((section) => section.order); if (new Set(orders).size !== orders.length || orders.some((order, index) => order !== index)) throw new OutlineError("invalid_output", "Outline sections must use consecutive order values.");
  return { output: result, ...(response.returnedModelId ? { returnedModelId: response.returnedModelId } : {}) };
}
