import type { ProviderCredentialStore, TextCertificationStore } from "@lsf/db";
import { outlineOutputSchema } from "@lsf/domain";
import { TextProviderError, type TextProvider } from "@lsf/providers";
import { resolveActiveTextProvider } from "./textProviderService";

export class OutlineError extends Error { constructor(readonly category: "capability_not_verified" | "credential_missing" | "provider_failed" | "invalid_json" | "invalid_output", message: string) { super(message); } }
type TextClient = Pick<TextProvider, "generateStructured">;

export async function runOutline(input: { idea: Record<string, unknown>; storyArchitecture?: Record<string, unknown>; claims: Array<{ id: string; state: string; approvalState: string }>; profile: Record<string, unknown>; targetDuration: string; language: string; credentialStore: ProviderCredentialStore; certificationStore: TextCertificationStore; createClient?: (config: { baseUrl: string; apiKey: string }) => TextClient }) {
  let configured: { provider: TextProvider; model: string }; try { configured = await resolveActiveTextProvider({ credentialStore: input.credentialStore, certificationStore: input.certificationStore }); } catch (error) { throw new OutlineError(error instanceof TextProviderError ? "capability_not_verified" : "credential_missing", "Verified Cockpit text capability is required before Outline can run."); }
  const targetDurationSeconds = parseTargetDurationSeconds(input.targetDuration);
  const assumedWordsPerMinute = selectedWordsPerMinute(input.profile);
  const targetWords = Math.max(1, Math.round(targetDurationSeconds * assumedWordsPerMinute / 60));
  const prompt = `Create an outline only from the approved idea, approved Story Architecture, and focused channel profile. The target language is ${input.language}. This is a hard requirement: write every human-readable field in ${input.language}; do not write the outline in English unless English is the target language. Return strict JSON with targetDurationSeconds, targetWords, assumedWordsPerMinute, and sections. Every section must use exactly {"id":string,"order":integer starting at 0,"purpose":string,"narrativeRole":string,"keyPoint":string,"storyBeatIds":string[],"linkedClaimIds":string[],"dramaticFunction":string,"estimatedWords":positive integer,"estimatedSeconds":positive integer,"retentionIntent":string,"openLoop"?:string,"proofObjects":string[]}. Every section must map to an approved story beat. linkedClaimIds may be empty because this workflow does not use web research or Claim Map. Do not fact-check, browse, create claims, scenes, shots, or image prompts. Respect the supplied planning budget exactly.\n${JSON.stringify({ idea: input.idea, storyArchitecture: input.storyArchitecture, profile: focusedProfile(input.profile), planning: { targetDurationSeconds, targetWords, assumedWordsPerMinute }, targetLanguage: input.language })}`;
  let response: { data: ReturnType<typeof outlineOutputSchema.parse>; returnedModelId?: string }; try { const client = input.createClient?.({ baseUrl: "", apiKey: "" }); response = client ? await client.generateStructured({ model: configured.model, input: prompt, schema: outlineOutputSchema, timeoutMs: 60_000 }) : await configured.provider.generateStructured({ model: configured.model, input: prompt, schema: outlineOutputSchema, timeoutMs: 60_000 }); } catch (error) { if (error instanceof TextProviderError && error.code === "invalid_json") throw new OutlineError("invalid_json", "Outline returned invalid JSON."); if (error instanceof TextProviderError && error.code === "schema_validation_failed") throw new OutlineError("invalid_output", "Outline returned an invalid structured output."); throw new OutlineError("provider_failed", "Outline text provider request failed."); }
  const result = response.data;
  const allowedClaims = new Set(input.claims.filter((claim) => claim.approvalState === "allowed" && claim.state === "verified").map((claim) => claim.id));
  if (result.sections.some((section) => section.linkedClaimIds.some((id) => !allowedClaims.has(id)))) throw new OutlineError("invalid_output", "Outline linked unsupported or unknown claims.");
  const orders = result.sections.map((section) => section.order); if (new Set(orders).size !== orders.length || orders.some((order, index) => order !== index)) throw new OutlineError("invalid_output", "Outline sections must use consecutive order values.");
  const beatIds = new Set(Array.isArray(input.storyArchitecture?.beats) ? input.storyArchitecture.beats.flatMap((beat) => typeof beat === "object" && beat !== null && typeof (beat as { id?: unknown }).id === "string" ? [(beat as { id: string }).id] : []) : []);
  if (beatIds.size && result.sections.some((section) => section.storyBeatIds.some((id) => !beatIds.has(id)))) throw new OutlineError("invalid_output", "Outline linked an unknown Story Architecture beat.");
  if (result.targetDurationSeconds !== targetDurationSeconds || result.targetWords !== targetWords || result.assumedWordsPerMinute !== assumedWordsPerMinute) throw new OutlineError("invalid_output", "Outline planning metadata did not match the selected duration and narration rate.");
  const plannedWords = result.sections.reduce((total, section) => total + section.estimatedWords, 0);
  if (Math.abs(plannedWords - targetWords) > Math.max(20, Math.round(targetWords * 0.2))) throw new OutlineError("invalid_output", "Outline word plan does not respect the target duration.");
  return { output: result, ...(response.returnedModelId ? { returnedModelId: response.returnedModelId } : {}) };
}

function parseTargetDurationSeconds(value: string): number { const match = value.trim().match(/(\d+(?:\.\d+)?)\s*(seconds?|secs?|s|minutes?|mins?|m)?/i); if (!match) return 300; const amount = Number(match[1]); const unit = match[2]?.toLowerCase() ?? "m"; return Math.max(1, Math.round(amount * (unit.startsWith("s") ? 1 : 60))); }
function selectedWordsPerMinute(profile: Record<string, unknown>): number { const candidate = profile.wordsPerMinute ?? profile.narrationWordsPerMinute; return typeof candidate === "number" && Number.isInteger(candidate) && candidate >= 80 && candidate <= 240 ? candidate : 150; }
function focusedProfile(profile: Record<string, unknown>): Record<string, unknown> { const fields = ["targetAudience", "mainKeyword", "niche", "tone", "language", "positioning", "avoidList", "safetyRules", "wordsPerMinute", "narrationWordsPerMinute"]; return Object.fromEntries(fields.flatMap((field) => profile[field] === undefined ? [] : [[field, profile[field]]])); }
