import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { MemoryKeychain, openFactoryDatabase, ProviderCredentialStore, TextCertificationStore } from "@lsf/db";
import { fingerprintBaseUrl } from "./nineRouterTextCertificationService";
import { runOutline } from "./outlineService";
async function setup() { const db = openFactoryDatabase(join(mkdtempSync(join(tmpdir(), "lsf-outline-")), "factory.sqlite")); const credentialStore = new ProviderCredentialStore(db, new MemoryKeychain()); const certificationStore = new TextCertificationStore(db); await credentialStore.saveProviderCredential({ providerId: "cockpit", baseUrl: "http://127.0.0.1:20128/v1", textModel: "outline-v1" }, "sk-secret"); certificationStore.saveTextCertificationRecord({ id: "cert-outline", providerId: "cockpit", configuredModelId: "outline-v1", baseUrlFingerprint: fingerprintBaseUrl("http://127.0.0.1:20128/v1")!, credentialVersionRef: credentialStore.loadProviderCredentialVersionRef("cockpit"), endpointStrategy: "responses", implementationVersion: "text-capability-v1", exactTextTest: { status: "passed", latencyMs: 1 }, strictJsonTest: { status: "passed", latencyMs: 1 }, overallStatus: "verified", testedAt: "2026-07-30T00:00:00.000Z" }); return { db, credentialStore, certificationStore }; }
const output = { sections: [{ id: "section-1", order: 0, purpose: "Hook", keyPoint: "Explain the verified claim.", linkedClaimIds: ["claim-1"], dramaticFunction: "Open a question", estimatedSeconds: 45, proofObjects: ["Source excerpt"] }] };
describe("outline service", () => { it("accepts sections linked to allowed verified claims", async () => { const { db, credentialStore, certificationStore } = await setup(); const result = await runOutline({ idea: { workingTitle: "Topic" }, claims: [{ id: "claim-1", state: "verified", approvalState: "allowed" }], profile: {}, targetDuration: "60 seconds", language: "Vietnamese", credentialStore, certificationStore, createClient: () => ({ createResponseText: async () => ({ text: JSON.stringify(output) }) }) }); expect(result.output.sections).toHaveLength(1); db.close(); }); it("includes the target language in the model prompt", async () => { const { db, credentialStore, certificationStore } = await setup(); let prompt = ""; await runOutline({ idea: {}, claims: [], profile: {}, targetDuration: "60 seconds", language: "Vietnamese", credentialStore, certificationStore, createClient: () => ({ createResponseText: async (request) => { prompt = request.input; return { text: JSON.stringify({ sections: [{ ...output.sections[0], linkedClaimIds: [] }] }) }; } }) }); expect(prompt).toContain("target language is Vietnamese"); db.close(); }); it("rejects unsupported claim links", async () => { const { db, credentialStore, certificationStore } = await setup(); await expect(runOutline({ idea: {}, claims: [{ id: "claim-1", state: "unsupported", approvalState: "blocked" }], profile: {}, targetDuration: "60 seconds", language: "Vietnamese", credentialStore, certificationStore, createClient: () => ({ createResponseText: async () => ({ text: JSON.stringify(output) }) }) })).rejects.toMatchObject({ category: "invalid_output" }); db.close(); }); });
it("accepts an outline without claims", async () => { const { db, credentialStore, certificationStore } = await setup(); const result = await runOutline({ idea: { workingTitle: "Topic" }, claims: [], profile: {}, targetDuration: "60 seconds", language: "Vietnamese", credentialStore, certificationStore, createClient: () => ({ createResponseText: async () => ({ text: JSON.stringify({ sections: [{ ...output.sections[0], linkedClaimIds: [] }] }) }) }) }); expect(result.output.sections[0]?.linkedClaimIds).toEqual([]); db.close(); });
