import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { MemoryKeychain, openFactoryDatabase, ProviderCredentialStore, TextCertificationStore } from "@lsf/db";
import { fingerprintBaseUrl } from "./nineRouterTextCertificationService";
import { runPromptPreparation } from "./promptPreparationService";

describe("prompt preparation service", () => { it("rejects prompts not bound exactly to approved AI-routed shots", async () => { const db = openFactoryDatabase(join(mkdtempSync(join(tmpdir(), "lsf-prompts-")), "factory.sqlite")); const credentials = new ProviderCredentialStore(db, new MemoryKeychain()); const certifications = new TextCertificationStore(db); await credentials.saveProviderCredential({ providerId: "9router", baseUrl: "http://127.0.0.1:20128/v1", textModel: "prompt-v1" }, "sk-secret"); certifications.saveTextCertificationRecord({ id: "cert-prompts", providerId: "9router", configuredModelId: "prompt-v1", baseUrlFingerprint: fingerprintBaseUrl("http://127.0.0.1:20128/v1")!, credentialVersionRef: credentials.loadProviderCredentialVersionRef("9router"), endpointStrategy: "responses", implementationVersion: "text-certification-v1", exactTextTest: { status: "passed", latencyMs: 1 }, strictJsonTest: { status: "passed", latencyMs: 1 }, overallStatus: "verified", testedAt: "2026-07-30T00:00:00.000Z" }); const input = { shots: [{ id: "shot-1", visualMode: "ai_image", framing: "Close", cameraAngle: "Eye", cameraMovement: "Static", subjectAction: "Reveal", continuityRefs: [] }], aspectRatio: "16:9" as const, credentialStore: credentials, certificationStore: certifications, createClient: () => ({ createResponseText: async () => ({ text: JSON.stringify({ prompts: [{ shotId: "missing", promptVersionId: "prompt-1", positivePrompt: "subject", negativePrompt: "text", aspectRatio: "16:9", continuityConstraints: [], prohibitedElements: [] }] }) }) }) }; await expect(runPromptPreparation(input)).rejects.toMatchObject({ category: "invalid_output" }); db.close(); }); });
