import type { ProviderCredentialStore, TextCertificationStore } from "@lsf/db";
import { scenePlanOutputSchema } from "@lsf/domain";
import { TextProviderError, type TextProvider } from "@lsf/providers";
import { adaptLegacyTextClient, type LegacyTextClient, resolveActiveTextProvider } from "./textProviderService";

export class ScenePlanError extends Error { constructor(readonly category: "capability_not_verified" | "credential_missing" | "provider_failed" | "invalid_json" | "invalid_output", message: string) { super(message); } }
type TextClient = Pick<TextProvider, "generateStructured"> | LegacyTextClient;

export async function runScenePlan(input: { script: { sections: Array<{ id: string; narration: string; purpose: string; estimatedSeconds: number; proofObjects: string[] }> }; fps: number; credentialStore: ProviderCredentialStore; certificationStore: TextCertificationStore; createClient?: (config: { baseUrl: string; apiKey: string }) => TextClient }) {
  let configured: { provider: TextProvider; model: string };
  try { configured = await resolveActiveTextProvider({ credentialStore: input.credentialStore, certificationStore: input.certificationStore }); } catch (error) { throw new ScenePlanError(error instanceof TextProviderError ? "capability_not_verified" : "credential_missing", "Verified Cockpit text capability is required before Scene Plan can run."); }
  const prompt = `Create a scene plan from this reviewed script. Return strict JSON {"fps":integer,"scenes":[...]}. Each scene must use exactly {"id":string,"scriptSectionId":string,"narration":string,"purpose":string,"startFrame":nonnegative integer,"durationFrames":positive integer,"visualMode":"ai_image"|"ai_video"|"stock_image"|"stock_video"|"manual_upload"|"uploaded"|"document"|"diagram"|"text_card"|"reuse","proofObject"?:string,"emotionalState":string,"requiredAssets":string[],"continuityRefs":string[]}. Use startFrame plus durationFrames, never endFrame. Every scene maps once to a supplied scriptSectionId, preserves its narration exactly, and scenes must be consecutive from frame 0. Do not generate assets or shots.\n${JSON.stringify({ script: input.script, fps: input.fps })}`;
  let response: { data: ReturnType<typeof scenePlanOutputSchema.parse>; returnedModelId?: string };
  try { const injected = input.createClient?.({ baseUrl: "", apiKey: "" }); const client = injected && ("generateStructured" in injected ? injected : adaptLegacyTextClient(injected)); response = client ? await client.generateStructured({ model: configured.model, input: prompt, schema: scenePlanOutputSchema, timeoutMs: 60_000 }) : await configured.provider.generateStructured({ model: configured.model, input: prompt, schema: scenePlanOutputSchema, timeoutMs: 60_000 }); } catch (error) { if (error instanceof TextProviderError && error.code === "invalid_json") throw new ScenePlanError("invalid_json", "Scene Plan returned invalid JSON."); if (error instanceof TextProviderError && error.code === "schema_validation_failed") throw new ScenePlanError("invalid_output", "Scene Plan returned an invalid structured output."); throw new ScenePlanError("provider_failed", "Scene Plan text provider request failed."); }
  const result = response.data;
  const sectionsById = new Map(input.script.sections.map((section) => [section.id, section])); const scenes = result.scenes; const sceneSectionIds = scenes.map((scene) => scene.scriptSectionId);
  if (result.fps !== input.fps || scenes[0]?.startFrame !== 0 || new Set(sceneSectionIds).size !== input.script.sections.length || sceneSectionIds.length !== input.script.sections.length || scenes.some((scene) => !sectionsById.has(scene.scriptSectionId) || scene.narration !== sectionsById.get(scene.scriptSectionId)!.narration) || scenes.some((scene, index) => index > 0 && scene.startFrame !== scenes[index - 1]!.startFrame + scenes[index - 1]!.durationFrames)) throw new ScenePlanError("invalid_output", "Scene Plan must cover approved sections once, preserve narration, and use consecutive frame timing.");
  return { output: result, ...(response.returnedModelId ? { returnedModelId: response.returnedModelId } : {}) };
}
