import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { MemoryKeychain, openFactoryDatabase, ProviderCredentialStore, TextCertificationStore } from "@lsf/db";
import { buildChannelPromptProfile, createDefaultChannelDna } from "@lsf/domain";
import { fingerprintBaseUrl } from "./nineRouterTextCertificationService";
import { runScenePlan } from "./scenePlanService";

async function setup() { const db = openFactoryDatabase(join(mkdtempSync(join(tmpdir(), "lsf-scene-")), "factory.sqlite")); const credentials = new ProviderCredentialStore(db, new MemoryKeychain()); const certifications = new TextCertificationStore(db); await credentials.saveProviderCredential({ providerId: "9router", baseUrl: "http://127.0.0.1:20128/v1", textModel: "scene-v1" }, "sk-secret"); certifications.saveTextCertificationRecord({ id: "cert", providerId: "9router", configuredModelId: "scene-v1", baseUrlFingerprint: fingerprintBaseUrl("http://127.0.0.1:20128/v1")!, credentialVersionRef: credentials.loadProviderCredentialVersionRef("9router"), endpointStrategy: "responses", implementationVersion: "text-certification-v1", exactTextTest: { status: "passed", latencyMs: 1 }, strictJsonTest: { status: "passed", latencyMs: 1 }, overallStatus: "verified", testedAt: "2026-07-30T00:00:00.000Z" }); return { db, credentials, certifications }; }

const script = { sections: [{ id: "script-1", narration: "Narration.", purpose: "Hook", estimatedSeconds: 2, proofObjects: [] }] };
const output = { fps: 30, scenes: [{ id: "scene-1", scriptSectionId: "script-1", narration: "Narration.", purpose: "Hook", startFrame: 0, durationFrames: 60, visualMode: "document", emotionalState: "Curious", requiredAssets: [], continuityRefs: [] }] };

describe("scene plan service", () => {
  it("requires consecutive scene timing", async () => { const { db, credentials, certifications } = await setup(); await expect(runScenePlan({ script, fps: 30, credentialStore: credentials, certificationStore: certifications, createClient: () => ({ createResponseText: async () => ({ text: JSON.stringify(output) }) }) })).resolves.toMatchObject({ output }); db.close(); });
  it("rejects scenes that rewrite approved narration", async () => { const { db, credentials, certifications } = await setup(); await expect(runScenePlan({ script, fps: 30, credentialStore: credentials, certificationStore: certifications, createClient: () => ({ createResponseText: async () => ({ text: JSON.stringify({ ...output, scenes: [{ ...output.scenes[0], narration: "Changed narration." }] }) }) }) })).rejects.toMatchObject({ category: "invalid_output" }); db.close(); });
  it("rejects scene plans that skip an approved script section", async () => { const { db, credentials, certifications } = await setup(); const twoSectionScript = { sections: [...script.sections, { id: "script-2", narration: "Second narration.", purpose: "Payoff", estimatedSeconds: 2, proofObjects: [] }] }; await expect(runScenePlan({ script: twoSectionScript, fps: 30, credentialStore: credentials, certificationStore: certifications, createClient: () => ({ createResponseText: async () => ({ text: JSON.stringify(output) }) }) })).rejects.toMatchObject({ category: "invalid_output" }); db.close(); });
  it("rejects scene plans that leave an initial timing gap", async () => { const { db, credentials, certifications } = await setup(); await expect(runScenePlan({ script, fps: 30, credentialStore: credentials, certificationStore: certifications, createClient: () => ({ createResponseText: async () => ({ text: JSON.stringify({ ...output, scenes: [{ ...output.scenes[0], startFrame: 30 }] }) }) }) })).rejects.toMatchObject({ category: "invalid_output" }); db.close(); });
  it("passes the selected channel storyboard grammar to the provider", async () => { const { db, credentials, certifications } = await setup(); const channelPromptProfile = buildChannelPromptProfile({ channelId: "milo-red-panda", channelDna: createDefaultChannelDna({ styleId: "cute-daily-life-cartoon" }) }); let request = ""; await runScenePlan({ script, fps: 30, channelPromptProfile, credentialStore: credentials, certificationStore: certifications, createClient: () => ({ createResponseText: async (input) => { request = input.input; return { text: JSON.stringify(output) }; } }) }); expect(request).toContain("milo-red-panda"); expect(request).toContain("character objective"); db.close(); });
});
