import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { MemoryKeychain, openFactoryDatabase, ProviderCredentialStore, TextCertificationStore } from "@lsf/db";
import { fingerprintBaseUrl } from "./nineRouterTextCertificationService";
import { runScenePlan } from "./scenePlanService";

describe("scene plan service", () => { it("requires consecutive scene timing", async () => { const db = openFactoryDatabase(join(mkdtempSync(join(tmpdir(), "lsf-scene-")), "factory.sqlite")); const credentials = new ProviderCredentialStore(db, new MemoryKeychain()); const certifications = new TextCertificationStore(db); await credentials.saveProviderCredential({ providerId: "9router", baseUrl: "http://127.0.0.1:20128/v1", textModel: "scene-v1" }, "sk-secret"); certifications.saveTextCertificationRecord({ id: "cert", providerId: "9router", configuredModelId: "scene-v1", baseUrlFingerprint: fingerprintBaseUrl("http://127.0.0.1:20128/v1")!, credentialVersionRef: credentials.loadProviderCredentialVersionRef("9router"), endpointStrategy: "responses", implementationVersion: "text-certification-v1", exactTextTest: { status: "passed", latencyMs: 1 }, strictJsonTest: { status: "passed", latencyMs: 1 }, overallStatus: "verified", testedAt: "2026-07-30T00:00:00.000Z" }); const output = { fps: 30, scenes: [{ id: "scene-1", scriptSectionId: "script-1", narration: "Narration.", purpose: "Hook", startFrame: 0, durationFrames: 60, visualMode: "document", emotionalState: "Curious", requiredAssets: [], continuityRefs: [] }] }; await expect(runScenePlan({ script: { sections: [{ id: "script-1", narration: "Narration.", purpose: "Hook", estimatedSeconds: 2, proofObjects: [] }] }, fps: 30, credentialStore: credentials, certificationStore: certifications, createClient: () => ({ createResponseText: async () => ({ text: JSON.stringify(output) }) }) })).resolves.toMatchObject({ output }); db.close(); }); });
