import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { MemoryKeychain, openFactoryDatabase, ProviderCredentialStore, TextCertificationStore } from "@lsf/db";
import { fingerprintBaseUrl } from "./nineRouterTextCertificationService";
import { runShotPlan } from "./shotPlanService";

async function setup() { const db = openFactoryDatabase(join(mkdtempSync(join(tmpdir(), "lsf-shots-")), "factory.sqlite")); const credentialStore = new ProviderCredentialStore(db, new MemoryKeychain()); const certificationStore = new TextCertificationStore(db); await credentialStore.saveProviderCredential({ providerId: "9router", baseUrl: "http://127.0.0.1:20128/v1", textModel: "shots-v1" }, "sk-secret"); certificationStore.saveTextCertificationRecord({ id: "cert-shots", providerId: "9router", configuredModelId: "shots-v1", baseUrlFingerprint: fingerprintBaseUrl("http://127.0.0.1:20128/v1")!, credentialVersionRef: credentialStore.loadProviderCredentialVersionRef("9router"), endpointStrategy: "responses", implementationVersion: "text-certification-v1", exactTextTest: { status: "passed", latencyMs: 1 }, strictJsonTest: { status: "passed", latencyMs: 1 }, overallStatus: "verified", testedAt: "2026-07-30T00:00:00.000Z" }); return { db, credentialStore, certificationStore }; }

describe("shot plan service", () => {
  it("accepts shots fully contained within approved scenes", async () => { const { db, credentialStore, certificationStore } = await setup(); const output = { shots: [{ id: "shot-1", sceneId: "scene-1", order: 0, startFrame: 0, durationFrames: 30, fps: 30, purpose: "Open", visualMode: "document", framing: "Close", cameraAngle: "Eye level", cameraMovement: "Static", subjectAction: "Reveal", startState: {}, endState: {}, continuityRefs: [] }] }; await expect(runShotPlan({ scenes: [{ id: "scene-1", startFrame: 0, durationFrames: 60 }], fps: 30, credentialStore, certificationStore, createClient: () => ({ createResponseText: async () => ({ text: JSON.stringify(output) }) }) })).resolves.toMatchObject({ output }); db.close(); });
  it("rejects shots outside an approved scene", async () => { const { db, credentialStore, certificationStore } = await setup(); const output = { shots: [{ id: "shot-1", sceneId: "scene-1", order: 0, startFrame: 45, durationFrames: 30, fps: 30, purpose: "Overrun", visualMode: "document", framing: "Close", cameraAngle: "Eye level", cameraMovement: "Static", subjectAction: "Reveal", startState: {}, endState: {}, continuityRefs: [] }] }; await expect(runShotPlan({ scenes: [{ id: "scene-1", startFrame: 0, durationFrames: 60 }], fps: 30, credentialStore, certificationStore, createClient: () => ({ createResponseText: async () => ({ text: JSON.stringify(output) }) }) })).rejects.toMatchObject({ category: "invalid_output" }); db.close(); });
});
